#ifndef _FINANCE_DISPLAY_CONST_DEF_H_
#define _FINANCE_DISPLAY_CONST_DEF_H_

#define STATUS_UNDEFINED 0
#define STATUS_CONN_WIFI 1
#define STATUS_CONNECTED 2

#endif /* _FINANCE_DISPLAY_CONST_DEF_H_ */
